_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 50
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
        visualize:
            roc_curves:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curves - Epoch 9
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_curves_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
